version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

orbs:
  node: circleci/node@3.0.0

jobs:
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm pub

workflows:
  version: 2
  package-deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
